export interface RunRule {
  title: string;
  description: string;
}

const RULES_DB: Record<number, RunRule[]> = {
  1: [
    { title: "Dieta Vegana 🌱", description: "Nada de industrializados! Seu time só consome o que a natureza oferece: Potions, Antidotes e qualquer remédio comprado são PROIBIDOS. A cura vem de Berries, Fresh Water, Soda Pop e Lemonade, tudo “natural”, claro. E como todo bom ativista, não basta falar: você deve capturar 10 Pokémon do tipo Grama ou Inseto e libertá-los no final da run. Porque nada prova mais seu amor pela causa do que um gesto simbólico… e totalmente inconveniente." },
    { title: "Explorador Raiz 🥾", description: "Bike? Pra quê? Se não for pra gastar a sola do tênis, nem vale a jornada. A bicicleta está terminantemente proibida. Aqui é tudo no modo perna, como os antigos mestres queriam. E nada de chegar na cidade só pra beijar a insígnia: antes de encarar o Ginásio, você DEVE varrer todas as rotas conectadas e derrotar absolutamente TODOS os treinadores. Sem atalhos, sem preguiça, sem GPS. Só você, o caminho… e o cansaço acumulado." },
    { title: "Mochila Pequena 🎒", description: "Sua coluna já viu coisas demais nessa jornada, então chegou a hora de respeitar seus limites. Sua mochila não é um depósito de farmácia: você só pode carregar até 4 tipos diferentes de itens de cura ao mesmo tempo. Achou um quinto tipo? Sem choro, escolha um dos existentes e descarte ou venda na hora. Organização é importante, mas aqui é mais uma questão de sobrevivência ortopédica. Leve menos peso… ou pague com a lombar." },
    { title: "Moda Kanto 🎀", description: "Você não é só um treinador, você é um desfile ambulante. Em Kanto, estilo vem antes de qualquer coisa, inclusive da lógica de batalha. Todo Pokémon do seu time principal deve estar sempre segurando algum item. Estar sem acessório é praticamente crime fashion. E claro, o jogo deve ser jogado no modo “Set”, sem aviso de troca do oponente. Se vai perder, que seja com elegância e convicção. Afinal, ganhar é importante… mas perder com estilo é arte." },
    { title: "Level Cap Suave 📊", description: "Ser um treinador respeitável significa não humilhar o sistema. Seu time não pode ultrapassar mais de 2 níveis acima do Pokémon mais forte do próximo Líder de Ginásio, nada de overlevel. Passou do limite? Sem drama, o Pokémon vai direto pra Box e fica lá descansando (ou refletindo sobre suas escolhas) até você conquistar a insígnia correspondente. Aqui a progressão é controlada e disciplinada." },
  ],
  2: [
    { title: "Pipoqueiro 🍿", description: "No meio da batalha você simplesmente entra em modo pânico total e perde qualquer capacidade de raciocínio estratégico: itens estão proibidos durante combates, seja cura, status ou revives, a mochila vira só decoração. Você luta no improviso, na coragem e no desespero. Quando tudo termina e o pânico passa, aí sim você pode usar seus itens e cuidar do time normalmente, como se nada tivesse acontecido." },
    { title: "Síndrome do Irmão Caçula 👶", description: "Seu starter nunca superou o fato de ter sido “substituído pelos mais novos”. Pra manter o drama familiar vivo, ele JAMAIS pode ser mais forte que o membro mais fraco da equipe. No fim do dia, continua sendo o caçula carente pedindo atenção. Cuide dele, ou pelo menos finja melhor." },
    { title: "O Purista de Batalha ⚔️", description: "Batalha, pra você, tem que ser no soco limpo da alma e sem truques baratos. Itens de status como X-Attack, X-Defend e Dire Hit estão completamente banidos — aqui não existe “buff”, só coragem e arrependimento. Também é proibido qualquer golpe que mexa com evasão ou precisão, como Double Team ou Sand Attack. Ou você acerta ou você aceita o destino. Simples, honesto e levemente cruel." },
    { title: "Amnésia Forçada 🧠", description: "Planejamento? Consistência? Esquece tudo. Antes de cada batalha de Ginásio, você é obrigado a bagunçar o próprio time ensinando pelo menos 1 TM diferente pra algum Pokémon. Não importa se o golpe é inútil, redundante ou completamente sem sentido — tem que entrar. Seu time vive em constante crise de identidade, desaprendendo o que prestava pra dar espaço a decisões duvidosas. Adaptar-se é obrigatório… sobreviver com isso já é outra história." },
    { title: "Catarata Pokébola 🔴", description: "Visão seletiva no auge: pra você, só existe a clássica Pokébola vermelha — o resto é luxo desnecessário. Todos os membros do seu time principal DEVEM ser capturados exclusivamente com ela, sem exceções. Great Balls e Ultra Balls até podem existir… mas só pra capturar os coitados destinados ao sacrifício. Cada captura importante vira um teste de paciência, insistência e leve sofrimento. Porque estilo retrô é bonito — até começar a dar errado." }
  ],
  3: [
    { title: "Fobia de Agulha 💉", description: "Seus Pokémon entram em colapso emocional ao ver a Enfermeira Joy e todo o ritual de cura. Por respeito ao trauma coletivo, você só pode usar o Centro Pokémon uma única vez por cidade — e acabou. Depois disso, a realidade bate: sobreviva com itens de cura ou faça a peregrinação humilhante de volta pra casa em Pallet pra dormir na cama da sua mãe e recuperar o time. É menos uma jornada de campeão e mais um vai-e-volta terapêutico com longas pausas emocionais." },
    { title: "Necromancia Terceirizada 💀", description: "Seu time não morre de verdade… mas a burocracia do além é cara. Sempre que um Pokémon do seu time principal desmaia, você não o revive de graça: precisa capturar 3 Pokémon selvagens e libertá-los permanentemente para “equilibrar o saldo espiritual”. Só então ele pode retornar no Centro Pokémon. Cada derrota vira uma pequena cadeia de sacrifícios administrativos, como se a morte tivesse taxa de serviço. Não há exceção nem piedade, só contabilidade de vidas para reativar o sistema." },
    { title: "Dieta do Carboidrato 🥤", description: "Centro Pokémon não é mais direito básico, é evento raro: uma visita por cidade e olhe lá. No resto do tempo, seu time vive de glicose, cafeína e decisões nutricionais questionáveis. A Vending Machine de Celadon vira sua farmácia oficial, como se refrigerante fosse protocolo médico aprovado pela Liga. E claro, disciplina rígida de sobrevivência urbana: você é obrigado a carregar sempre pelo menos 5 Fresh Waters, porque nada diz “treinador preparado” como depender de açúcar líquido pra manter criaturas lutando contra deuses locais." },
    { title: "Desafio do Rival 🏆", description: "Chegou na cidade achando que era checkpoint de descanso? Engraçado. Aqui não existe hospitalidade gratuita nem acesso civilizado ao Centro Pokémon/PC antes de prestar contas ao seu Rival. Ele te espera obrigatoriamente na rota como um auditor de caos pessoal, pronto pra lembrar que sua jornada não é turismo. Até derrotá-lo, você segue em modo sobrevivência improvisada: time remendado, recursos escassos e decisões cada vez mais duvidosas. Só depois da humilhação (ou de um milagre improvável) o sistema “autoriza” você a fingir que está no controle de novo." },
    { title: "Fiel Depositário 👑", description: "Todo time precisa de um “queridinho oficial”, e o seu já nasce condenado a essa função: o VIP. Ele não entra em rotação, não descansa, não negocia — ele vai estar em todos os Ginásios, goste você ou não. É protagonismo compulsório com síndrome de estrela em turnê eterna. Mas a fama cobra juros: se o VIP desmaiar, acabou o tratamento especial. Nada de ressurreição imediata — ele fica na geladeira emocional até você vencer o próximo Líder usando só 5 Pokémon. É pressão constante, favoritismo obrigatório e uma gestão de recursos claramente escrita por alguém sem noção de RH." },
  ],
  4: [
    { title: "Pacifista de Matinho 🕊️", description: "Derrotar Pokémon selvagem pra XP é visto como exploração predatória de inocentes, então está fora de cogitação. Se quiser evoluir, vai ter que lidar com gente de verdade: outros treinadores que também só queriam uma jornada tranquila. Nada de “farm silencioso” fingindo eficiência — aqui o crescimento é barulhento, socialmente constrangedor e levemente traumático pra todos os envolvidos. Se vai ficar mais forte, pelo menos tenha a decência de envolver terceiros que não pediram pra virar estatística de progresso." },
    { title: "Comunismo de XP ☭", description: "ABAIXO os privilégios DA ELITE overlevel! Aqui ninguém se destaca — todo mundo progride na mesma marcha nivelada pelo coletivo. Antes de cada Ginásio, sua equipe inteira deve ser equalizada no mesmo nível, sem exceções. Mérito individual é tratado como invenção suspeita de treinador preguiçoso querendo carry emocional. Se algum Pokémon tentar “brilhar sozinho”, será imediatamente trazido de volta à realidade estatística. No fim, todos são iguais… e igualmente responsabilizados pelo desastre." },
    { title: "Analfabetismo Tático 🚫", description: "Aqui não existe upgrade, só evolução sofrida no método original. TMs e Move Tutors estão completamente banidos — qualquer tentativa de “otimizar” o time é tratada como fraude intelectual. Seus 6 Pokémon vão encarar a Liga usando apenas golpes aprendidos naturalmente ao subir de nível, goste você ou não. Sem customização, sem criatividade assistida, só o kit básico que o jogo decidiu que era suficiente. Estratégia? Aqui é mais sobrevivência com o que caiu no colo mesmo." },
    { title: "O Gladiador Solitário 🛡️", description: "Modo SET não é opção — é sentença. E pra piorar, entrou em batalha de Ginásio ou Boss? Esquece troca: acabou a conversa, começou o duelo de verdade. O Pokémon que pisar em campo fica até o fim, seja vitória gloriosa ou desmaio constrangedor. Nada de “vou trocar pra counterar” ou “deixa eu pensar melhor” — aqui a estratégia é compromisso forçado até o último suspiro. É um ringue, não um revezamento." },
    { title: "A Vingança do Matinho 🌿", description: "Perdeu pra Pokémon selvagem? Então o matinho te marcou de volta. Cada vez que um dos seus desmaia pra um encontro aleatório, ele sofre uma “amnésia traumática seletiva”: você é obrigado a levá-lo ao Move Deleter e apagar o golpe mais forte dele. É a forma que a natureza encontrou de dizer “não era pra ter acontecido isso”. O resultado é um time emocionalmente abalado e cada vez menos eficiente, como se o próprio jogo estivesse te lembrando que humilhação também tem consequências permanentes." }
  ],
  5: [
    { title: "Pacto com o Diabo 😈", description: "Modo SET obrigatório, porque você já provou que não sabe lidar com escolhas simples. Sem itens em batalha, claro — seria perigoso demais te deixar confortável. Desmaiou um Pokémon? Ótimo, agora começa o pagamento da sua incompetência: solte 10 Pokémon da Box (que você ainda vai farmar de novo, brilhante estratégia) e jogue fora sua melhor TM como taxa por achar que tinha controle da situação. Não é pacto — é só você financiando seus próprios erros com juros altos." },
    { title: "Genética Amaldiçoada 🧬", description: "A natureza simplesmente desistiu do seu time. A tecla B será destruída de tanto uso porque evolução não existe pra você — nunca existiu, nunca vai existir. Nenhum dos 6 Pokémon do time principal pode evoluir, ponto final. Você vai encarar a Elite Four com forma base mesmo: Charmander, Squirtle, Pidgey e o resto das vítimas pré-históricas do seu planejamento. Um experimento cruel." },
    { title: "O Banqueiro Falido 🏦", description: "Você quebrou o sistema econômico do jeito mais humilhante possível: proibido comprar qualquer coisa em PokéMart o jogo inteiro. Nada de Pokébolas, nada de Potions, nada de Repel — você não é cliente, é problema estatístico. Sua sobrevivência depende exclusivamente do que cair no chão ou da generosidade duvidosa de NPCs que também não te respeitam. É uma jornada de “gestão de recursos” onde o recurso é basicamente sorte e vergonha na cara." },
    { title: "Esquadrão Manco 🤕", description: "Seu time não é versátil, é limitado por design e constrangimento. Cada um dos 6 Pokémon só pode ter no máximo 3 golpes úteis — o quarto slot vira uma cicatriz funcional: ou você apaga no Move Deleter assim que possível, ou enche de golpe inútil tipo Splash ou Tail Whip que existe só pra te lembrar que espaço mal gerenciado é castigo. Na prática, você entra em batalha com um time capado, subótimo e emocionalmente questionável, como se a própria equipe tivesse desistido de performar direito." },
    { title: "Caminho de Espinhos 🌵", description: "Perdeu um Pokémon? Ótimo, o jogo te taxa por incompetência: 1/6 dos seus PokéDollars vai embora como multa emocional. Tomou wipe out? Parabéns, você foi oficialmente à falência existencial — perde todo o dinheiro, todas as TMs e todos os itens, e renasce do zero com o time inteiro te julgando em silêncio. E sim, eles te odeiam agora. Pra fechar o pacote de humilhação logística, Fly é proibido. Você atravessa Kanto inteiro a pé, toda vez, como um aventureiro sem recursos, sem transporte e sem autoestima." },
    { title: "Miserável, Nu e Sozinho 🩲", description: "Você não está jogando dificuldade — está assinando um contrato de humilhação progressiva. Seu level cap já começa atrasado: sempre 2 níveis abaixo do Ás do próximo Ginásio, porque crescer demais seria otimismo. Sem itens equipados, sem itens em batalha, sem X-Attack e derivados de esperança artificial. Até vitaminas (HP Up, Protein e similares) foram banidas pra evitar qualquer ilusão de progresso. E pra completar o pacote: nada de evoluções finais — seu time fica preso no estágio básico, eternamente inacabado, como se o jogo dissesse “isso aqui não era pra dar certo mesmo”." }
  ]
};

export function getRandomChallenge(difficulty: number): RunRule {
  const safeDifficulty = Math.max(1, Math.min(5, difficulty));
  const rules = RULES_DB[safeDifficulty];
  return rules[Math.floor(Math.random() * rules.length)];
}

